sprint18_fest: Добавлена фича Подписки
tochmary/explore-with-me pull request #2
Opened 2022-10-20 19:51 UTC by tochmary

2022-10-20 20:08 UTC, GordPavel requested changes
Все бы неплохо, но не увидел, какие события пользователя записываются в БД. То есть тут же ожидается, что кто-то совершает действия и другой может увидеть список действий. А тут нигде нет сохранения действий пользователя

2022-10-20 20:08 UTC, GordPavel commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventService.java
> +    List<Event> getEventsByUsers(List<Long> userIds, Integer from, Integer size);
почему не Pageable?

2022-10-20 20:08 UTC, GordPavel commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +        log.debug("Получение списка событий, добавленных текущими пользователями:");
по уровням логгирования тогда скорее наоборот со следующей строчкой

2022-10-20 20:08 UTC, GordPavel commented on main-service/src/main/java/ru/practicum/mainservice/user/controller/publicC/UserController.java
> +public class UserController {
тогда уж FollowsController

2022-10-20 20:08 UTC, GordPavel commented on main-service/src/main/java/ru/practicum/mainservice/user/controller/publicC/UserController.java
> +    @PatchMapping("/{followingId}")
POST метод вида `/users/{userId}/follows body {followingId}`

2022-10-20 20:08 UTC, GordPavel commented on main-service/src/main/java/ru/practicum/mainservice/user/controller/publicC/UserController.java
> +    @GetMapping("/events")
не совсем понимаю, зачем нужна сущность подписки, если все события пользователя можно и так посмотреть. Я бы тогда добавил возможность не подтверждать подписку и смотреть на статус подписки, когда запрашиваются события

2022-10-21 10:43 UTC, tochmary commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventService.java
> +    List<Event> getEventsByUsers(List<Long> userIds, Integer from, Integer size);
Pageable при вы зове метода репозитория далее.

2022-10-21 10:51 UTC, tochmary commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +        log.debug("Получение списка событий, добавленных текущими пользователями:");
Да, я здесь хотела debug

2022-10-21 11:47 UTC, tochmary commented on main-service/src/main/java/ru/practicum/mainservice/user/controller/publicC/UserController.java
> +    @GetMapping("/events")
Здесь должны быть опубликованные события, я забыла вчера это добавить

2022-10-21 11:49 UTC, tochmary commented on main-service/src/main/java/ru/practicum/mainservice/user/controller/publicC/UserController.java
> +    @PatchMapping("/{followingId}")
Я делала по аналогии с другим эндпойнтом основного сервиса ![image](https://user-images.githubusercontent.com/87110697/197189009-3c4350bd-2339-4db7-a9b5-d51483658771.jpeg)
Но могу поменять, мне самой не нравится в этом месте использовать patch, так как мы добавляем а не изменяем

2022-10-21 11:50 UTC, tochmary commented
Не совсем поняла этот комментарий так как состояния у события есть и находится в поле states.

2022-10-22 11:45 UTC, GurevVikrot approved these changes

2022-10-22 11:45 UTC, GurevVikrot commented on main-service/src/main/java/ru/practicum/mainservice/user/controller/publicC/FollowController.java
> +    public void removeFollowing(@PathVariable long userId,
Можно добавить аннотацию @Positive после @PathVarianle и добавить аннотацию над классом @Valedated.
Поможет отлавливать ошибки на этапе запроса к сервису валидации без выполнения лишних действий программой. Будет валидировать id пользователя и возвращать ошибку клиенту, когда приходит null, отрицательные значения или 0. 
Сейчас у тебя ошибка возникает на уровне БД, а этот способ поможет разгрузить программу и исключить лишние запросы к БД.
Аналогично и в других местах контролеров.

2022-10-22 11:45 UTC, GurevVikrot commented on main-service/src/main/java/ru/practicum/mainservice/user/controller/publicC/FollowController.java
> +        return EventMapper.getEventShortDtoList(eventList);
Я бы зауснул маппинг событий в сервис, чтобы контроллер сразу получал запрашиваемое

2022-10-22 11:45 UTC, GurevVikrot commented on main-service/src/main/java/ru/practicum/mainservice/user/controller/publicC/FollowController.java
> +                                                @PositiveOrZero @RequestParam(defaultValue = "0") Integer from,
лучше использовать примитив int для from и size, поможет в какой-то мере экономить память. Но это так, вкусовщина

2022-10-22 11:45 UTC, GurevVikrot commented on main-service/src/main/java/ru/practicum/mainservice/event/repository/EventRepository.java
> +    Page<Event> getEventsByInitiatorIdInAndPublishedOnIsNotNull(List<Long> userIDs, Pageable pageable);
Думаю не совсем верно возвращать все опубликованные события автора пользователя подпищику, часть событий уже могла завершится.
В идеале добавить еще один метод - получить все актуальные события автора, т.е. которые будут в будущем.
И оставить этот метод, чтобы можно было посмотреть все события автора

2022-10-23 09:05 UTC, merged